### ISSUE TITLE
Eclipse crash while running ALISA assurance case

### ISSUE THREAD

**Issue by smithdtyler** [osate/alisa#41]
Ran an assurance case that included JUnit and property verification. 

System information:

```
  Open Source AADL Tool Environment	2.3.2.v20180209-1848	org.osate.core.feature.feature.group	CMU SEI
  ALISA Requirement Specification and Verification	1.0.0.v20171018-1451	org.osate.alisa.workbench.sdk.feature.group	null
  ALISA Requirement Specification and Verification Developer Resources	1.0.0.v20171018-1451	org.osate.alisa.workbench.sdk.source.feature.group	null
```

Eclipse hung with this stack trace:

```
!MESSAGE To avoid deadlock while executing Display.syncExec() with argument: org.osate.ge.internal.services.impl.DefaultModelChangeNotifier$$Lambda$463/800390097@1c58ac4, thread Worker-24 will interrupt UI thread.
!SUBENTRY 1 org.eclipse.ui 4 4 2018-03-26 12:49:34.657
!MESSAGE Worker-24 thread is an instance of Worker or owns an ILock
!STACK 0
java.lang.IllegalStateException: Call stack for thread Worker-24
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:448)
	at org.eclipse.ui.internal.UILockListener.reportInterruption(UILockListener.java:206)
	at org.eclipse.ui.internal.UILockListener.interruptUI(UILockListener.java:176)
	at org.eclipse.ui.internal.PendingSyncExec.waitUntilExecuted(PendingSyncExec.java:82)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4889)
	at org.osate.ge.internal.services.impl.DefaultModelChangeNotifier.lambda$0(DefaultModelChangeNotifier.java:98)
	at org.osate.ge.internal.services.impl.DefaultModelChangeNotifier$$Lambda$97/1787512748.resourceChanged(Unknown Source)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
!SUBENTRY 1 org.eclipse.ui 4 4 2018-03-26 12:49:34.672
!MESSAGE UI thread waiting on a job or lock.
!STACK 0
java.lang.IllegalStateException: Call stack for thread main
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
	at org.eclipse.core.internal.resources.Resource.deleteMarkers(Resource.java:796)
	at org.osate.aadl2.modelsupport.errorreporting.MarkerParseErrorReporter.deleteMessagesImpl(MarkerParseErrorReporter.java:117)
	at org.osate.aadl2.modelsupport.errorreporting.AbstractErrorReporter.deleteMessages(AbstractErrorReporter.java:56)
	at org.osate.aadl2.modelsupport.errorreporting.ParseErrorReporterManager.getReporter(ParseErrorReporterManager.java:116)
	at org.osate.xtext.aadl2.parsing.AnnexParserAgent.afterModelLinked(AnnexParserAgent.java:119)
	at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:57)
	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:340)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:107)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:301)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:169)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:290)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:161)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:180)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:100)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:80)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:247)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:220)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:201)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:261)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.osate.assure.assure.impl.ModelResultImpl.getTarget(ModelResultImpl.java:208)
	at org.osate.assure.ui.views.AlisaView$7$3$1.getText(AlisaView.java:755)
	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:34)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/36266279.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/36266279.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2159)
	at org.eclipse.jface.viewers.StructuredViewer.internalUpdate(StructuredViewer.java:2142)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2083)
	at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:542)
	at org.osate.assure.ui.views.AlisaView.update(AlisaView.java:1431)
	at org.osate.assure.ui.views.AlisaView$11.accept(AlisaView.java:1262)
	at org.osate.assure.ui.views.AlisaView$11.accept(AlisaView.java:1)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.osate.assure.ui.views.AlisaView.updateAllAssureResult(AlisaView.java:1265)
	at org.osate.assure.ui.views.AlisaView.updateAssureViewer(AlisaView.java:1251)
	at org.osate.assure.ui.views.AlisaView.access$5(AlisaView.java:1201)
	at org.osate.assure.ui.views.AlisaView$1$4.run(AlisaView.java:276)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.ui.internal.Workbench$$Lambda$14/2014481872.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by lwrage** [comment]
Do you have a reproducible example?
